service:
  service_port:  ":50852"

mysql:
  uri: "root:12345678@tcp(127.0.0.1:3306)/mysgate_demo?charset=utf8mb4"
  show_sql: true

log:
  path: "./mysgate.log"
  level: "debug"
  
debug: true

chains:
  - name: "zkSync Era"
    chain_id: 280
    wss_rpc_url: "wss://testnet.era.zksync.dev/ws"
    http_rpc_url: "https://testnet.era.zksync.dev"
    contract_address: "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0"
    private_key: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
    support_coins:
      - "usdt"
  - name: "Scroll"
    chain_id: 534353
    wss_rpc_url: "wss://scroll-alphanet.blastapi.io/57226f34-917f-4e5d-84ed-76f527dac6ce"
    http_rpc_url: "https://alpha-rpc.scroll.io/l2"
    contract_address: "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0"
    private_key: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
    support_coins:
      - "usdt"

cross_chains:
  - src_chain_id: 280
    dest_chain_id: 534353

cross_chain_fees:
  - name: "eth"
    fixed: 0.01
    float_rate: 0.0001
  - name: "stablecoin"
    fixed: 1
    float_rate: 0.0001

cross_chain_coin_limit:
  - name: "eth"
    max_amount: 100000
    min_amount: 0.001
  - name: "stablecoin"
    max_amount: 100000
    min_amount: 0.01   

cross_chain_coins:
  - name: "eth"
    type: "eth"
  - name: "usdt"
    type: "stablecoin"
  - name: "usdc"
    type: "stablecoin"
  - name: "dai"
    type: "stablecoin"  

support_coins:
  - "usdt" 

router:
  type: "fixed"
  porters:
    - "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0"  

zkp_url: "http://127.0.0.1:2000/proof"